# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window_hashed_maze.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QCommandLinkButton, QFrame,
    QGridLayout, QGroupBox, QHBoxLayout, QHeaderView,
    QLabel, QLineEdit, QMainWindow, QMenuBar,
    QPlainTextEdit, QProgressBar, QPushButton, QSizePolicy,
    QSpacerItem, QStatusBar, QTabWidget, QTextEdit,
    QToolButton, QTreeWidget, QTreeWidgetItem, QVBoxLayout,
    QWidget)

from roundedframe import RoundedFrame

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(875, 692)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tab_search = QWidget()
        self.tab_search.setObjectName(u"tab_search")
        self.tab_search.setStyleSheet(u"")
        self.gridLayout_2 = QGridLayout(self.tab_search)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.frameCFG = QFrame(self.tab_search)
        self.frameCFG.setObjectName(u"frameCFG")
        self.frameCFG.setFrameShape(QFrame.Shape.StyledPanel)
        self.frameCFG.setFrameShadow(QFrame.Shadow.Raised)
        self.btnSearchBy = QToolButton(self.frameCFG)
        self.btnSearchBy.setObjectName(u"btnSearchBy")
        self.btnSearchBy.setGeometry(QRect(20, 24, 81, 26))
        self.edtSearch = QLineEdit(self.frameCFG)
        self.edtSearch.setObjectName(u"edtSearch")
        self.edtSearch.setGeometry(QRect(193, 26, 281, 23))
        self.treeCredentialsResponse = QTreeWidget(self.frameCFG)
        self.treeCredentialsResponse.setObjectName(u"treeCredentialsResponse")
        self.treeCredentialsResponse.setGeometry(QRect(11, 70, 810, 192))
        self.btnSearch = QPushButton(self.frameCFG)
        self.btnSearch.setObjectName(u"btnSearch")
        self.btnSearch.setGeometry(QRect(104, 25, 69, 24))
        self.lblIconSearch = QLabel(self.frameCFG)
        self.lblIconSearch.setObjectName(u"lblIconSearch")
        self.lblIconSearch.setGeometry(QRect(760, 10, 41, 41))
        self.frame_2 = QFrame(self.frameCFG)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(10, 270, 811, 220))
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.edtAccount = QLineEdit(self.frame_2)
        self.edtAccount.setObjectName(u"edtAccount")
        self.edtAccount.setGeometry(QRect(20, 40, 221, 23))
        self.edtURL = QLineEdit(self.frame_2)
        self.edtURL.setObjectName(u"edtURL")
        self.edtURL.setGeometry(QRect(20, 90, 491, 23))
        self.edtPWD = QLineEdit(self.frame_2)
        self.edtPWD.setObjectName(u"edtPWD")
        self.edtPWD.setGeometry(QRect(20, 140, 221, 23))
        self.edtPWD.setEchoMode(QLineEdit.EchoMode.Password)
        self.edtPlainNotes = QPlainTextEdit(self.frame_2)
        self.edtPlainNotes.setObjectName(u"edtPlainNotes")
        self.edtPlainNotes.setGeometry(QRect(550, 20, 231, 181))
        self.edtPlainNotes.setStyleSheet(u"")
        self.label = QLabel(self.frame_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(24, 20, 131, 16))
        self.label_2 = QLabel(self.frame_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(22, 70, 131, 16))
        self.label_8 = QLabel(self.frame_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(21, 120, 131, 16))
        self.btnApply = QPushButton(self.frame_2)
        self.btnApply.setObjectName(u"btnApply")
        self.btnApply.setEnabled(False)
        self.btnApply.setGeometry(QRect(404, 180, 64, 24))
        self.btnShowPWD = QPushButton(self.frame_2)
        self.btnShowPWD.setObjectName(u"btnShowPWD")
        self.btnShowPWD.setGeometry(QRect(244, 140, 23, 24))
        self.btnNew = QPushButton(self.frame_2)
        self.btnNew.setObjectName(u"btnNew")
        self.btnNew.setGeometry(QRect(20, 180, 64, 24))
        self.pBar = QProgressBar(self.frame_2)
        self.pBar.setObjectName(u"pBar")
        self.pBar.setGeometry(QRect(370, 140, 118, 23))
        self.pBar.setMaximum(0)
        self.pBar.setValue(-1)
        self.pBar.setTextVisible(True)
        self.frmStatusEdition = RoundedFrame(self.frame_2)
        self.frmStatusEdition.setObjectName(u"frmStatusEdition")
        self.frmStatusEdition.setGeometry(QRect(0, -2, 8, 221))
        self.frmStatusEdition.setToolTipDuration(-1)
        self.frmStatusEdition.setFrameShape(QFrame.Shape.StyledPanel)
        self.frmStatusEdition.setFrameShadow(QFrame.Shadow.Raised)
        self.btnCancel = QPushButton(self.frame_2)
        self.btnCancel.setObjectName(u"btnCancel")
        self.btnCancel.setEnabled(False)
        self.btnCancel.setGeometry(QRect(470, 180, 64, 24))
        self.btnHelpCredentials = QPushButton(self.frame_2)
        self.btnHelpCredentials.setObjectName(u"btnHelpCredentials")
        self.btnHelpCredentials.setGeometry(QRect(786, 3, 21, 24))
        self.btnGenRandomPWD = QPushButton(self.frame_2)
        self.btnGenRandomPWD.setObjectName(u"btnGenRandomPWD")
        self.btnGenRandomPWD.setGeometry(QRect(270, 140, 87, 24))
        self.lblStatusEditionOrError = QLabel(self.frameCFG)
        self.lblStatusEditionOrError.setObjectName(u"lblStatusEditionOrError")
        self.lblStatusEditionOrError.setGeometry(QRect(20, 498, 211, 16))
        self.lblSearchBy = QLabel(self.frameCFG)
        self.lblSearchBy.setObjectName(u"lblSearchBy")
        self.lblSearchBy.setGeometry(QRect(195, 49, 271, 16))
        self.lblSearchBy.setStyleSheet(u"")
        self.lblSearchBy.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lblResults = QLabel(self.frameCFG)
        self.lblResults.setObjectName(u"lblResults")
        self.lblResults.setGeometry(QRect(723, 51, 91, 18))
        self.lblResults.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.lblResults.setStyleSheet(u"")
        self.lblResults.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.btnHelpSearch = QPushButton(self.frameCFG)
        self.btnHelpSearch.setObjectName(u"btnHelpSearch")
        self.btnHelpSearch.setGeometry(QRect(809, 3, 21, 24))
        self.frmNavegationResults = QFrame(self.frameCFG)
        self.frmNavegationResults.setObjectName(u"frmNavegationResults")
        self.frmNavegationResults.setGeometry(QRect(482, 25, 211, 24))
        self.frmNavegationResults.setFrameShape(QFrame.Shape.StyledPanel)
        self.frmNavegationResults.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout = QHBoxLayout(self.frmNavegationResults)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(1, 0, 1, 0)
        self.btnFirst = QPushButton(self.frmNavegationResults)
        self.btnFirst.setObjectName(u"btnFirst")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFirst.sizePolicy().hasHeightForWidth())
        self.btnFirst.setSizePolicy(sizePolicy)

        self.horizontalLayout.addWidget(self.btnFirst)

        self.btnGoBack = QPushButton(self.frmNavegationResults)
        self.btnGoBack.setObjectName(u"btnGoBack")
        sizePolicy.setHeightForWidth(self.btnGoBack.sizePolicy().hasHeightForWidth())
        self.btnGoBack.setSizePolicy(sizePolicy)

        self.horizontalLayout.addWidget(self.btnGoBack)

        self.btnGoForward = QPushButton(self.frmNavegationResults)
        self.btnGoForward.setObjectName(u"btnGoForward")
        sizePolicy.setHeightForWidth(self.btnGoForward.sizePolicy().hasHeightForWidth())
        self.btnGoForward.setSizePolicy(sizePolicy)

        self.horizontalLayout.addWidget(self.btnGoForward)

        self.btnLast = QPushButton(self.frmNavegationResults)
        self.btnLast.setObjectName(u"btnLast")
        sizePolicy.setHeightForWidth(self.btnLast.sizePolicy().hasHeightForWidth())
        self.btnLast.setSizePolicy(sizePolicy)

        self.horizontalLayout.addWidget(self.btnLast)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.lblPagination = QLabel(self.frmNavegationResults)
        self.lblPagination.setObjectName(u"lblPagination")

        self.horizontalLayout.addWidget(self.lblPagination)


        self.gridLayout_2.addWidget(self.frameCFG, 0, 0, 1, 1)

        self.tabWidget.addTab(self.tab_search, "")
        self.tab_config = QWidget()
        self.tab_config.setObjectName(u"tab_config")
        self.gridLayout = QGridLayout(self.tab_config)
        self.gridLayout.setObjectName(u"gridLayout")
        self.frameCFG_2 = QFrame(self.tab_config)
        self.frameCFG_2.setObjectName(u"frameCFG_2")
        self.frameCFG_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frameCFG_2.setFrameShadow(QFrame.Shadow.Raised)
        self.lblIconConfig = QLabel(self.frameCFG_2)
        self.lblIconConfig.setObjectName(u"lblIconConfig")
        self.lblIconConfig.setGeometry(QRect(780, 10, 45, 41))
        self.gbxGeneral = QGroupBox(self.frameCFG_2)
        self.gbxGeneral.setObjectName(u"gbxGeneral")
        self.gbxGeneral.setGeometry(QRect(20, 20, 611, 191))
        self.cbxDefaultFieldSearch = QComboBox(self.gbxGeneral)
        self.cbxDefaultFieldSearch.addItem("")
        self.cbxDefaultFieldSearch.addItem("")
        self.cbxDefaultFieldSearch.addItem("")
        self.cbxDefaultFieldSearch.addItem("")
        self.cbxDefaultFieldSearch.addItem("")
        self.cbxDefaultFieldSearch.setObjectName(u"cbxDefaultFieldSearch")
        self.cbxDefaultFieldSearch.setGeometry(QRect(20, 54, 151, 24))
        self.label_9 = QLabel(self.gbxGeneral)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 34, 221, 16))
        self.label_10 = QLabel(self.gbxGeneral)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 90, 221, 16))
        self.cbxDefaultFieldOrder = QComboBox(self.gbxGeneral)
        self.cbxDefaultFieldOrder.addItem("")
        self.cbxDefaultFieldOrder.addItem("")
        self.cbxDefaultFieldOrder.addItem("")
        self.cbxDefaultFieldOrder.setObjectName(u"cbxDefaultFieldOrder")
        self.cbxDefaultFieldOrder.setGeometry(QRect(20, 110, 151, 24))
        self.cbxDefaultFieldOrder.setMaxVisibleItems(5)
        self.btnGeneralCFG = QPushButton(self.gbxGeneral)
        self.btnGeneralCFG.setObjectName(u"btnGeneralCFG")
        self.btnGeneralCFG.setGeometry(QRect(586, 13, 21, 24))
        self.lblSettings = QLabel(self.gbxGeneral)
        self.lblSettings.setObjectName(u"lblSettings")
        self.lblSettings.setGeometry(QRect(20, 160, 441, 20))
        self.lblSettings.setStyleSheet(u"QLabel{\n"
"	color:rgb(20, 182, 71)\n"
"}")
        self.lblSettings.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.cbxLogoffTime = QComboBox(self.gbxGeneral)
        self.cbxLogoffTime.addItem("")
        self.cbxLogoffTime.addItem("")
        self.cbxLogoffTime.addItem("")
        self.cbxLogoffTime.addItem("")
        self.cbxLogoffTime.setObjectName(u"cbxLogoffTime")
        self.cbxLogoffTime.setGeometry(QRect(310, 50, 111, 24))
        self.label_12 = QLabel(self.gbxGeneral)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(312, 30, 91, 16))
        self.label_13 = QLabel(self.gbxGeneral)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(314, 90, 91, 16))
        self.cbxColorScheme = QComboBox(self.gbxGeneral)
        self.cbxColorScheme.addItem("")
        self.cbxColorScheme.addItem("")
        self.cbxColorScheme.addItem("")
        self.cbxColorScheme.addItem("")
        self.cbxColorScheme.addItem("")
        self.cbxColorScheme.addItem("")
        self.cbxColorScheme.addItem("")
        self.cbxColorScheme.setObjectName(u"cbxColorScheme")
        self.cbxColorScheme.setGeometry(QRect(313, 110, 151, 24))
        self.lblCFGDatabaseDirectory = QLabel(self.frameCFG_2)
        self.lblCFGDatabaseDirectory.setObjectName(u"lblCFGDatabaseDirectory")
        self.lblCFGDatabaseDirectory.setGeometry(QRect(20, 500, 801, 19))
        self.lblCFGDatabaseDirectory.setStyleSheet(u"")
        self.lblCFGDatabaseDirectory_Title = QLabel(self.frameCFG_2)
        self.lblCFGDatabaseDirectory_Title.setObjectName(u"lblCFGDatabaseDirectory_Title")
        self.lblCFGDatabaseDirectory_Title.setGeometry(QRect(20, 489, 111, 16))
        self.lblCFGDatabaseDirectory_Title.setStyleSheet(u"")
        self.gbxChangePWD = QGroupBox(self.frameCFG_2)
        self.gbxChangePWD.setObjectName(u"gbxChangePWD")
        self.gbxChangePWD.setGeometry(QRect(20, 220, 611, 253))
        self.edtCurrentPWD = QLineEdit(self.gbxChangePWD)
        self.edtCurrentPWD.setObjectName(u"edtCurrentPWD")
        self.edtCurrentPWD.setGeometry(QRect(20, 38, 241, 21))
        self.edtCurrentPWD.setEchoMode(QLineEdit.EchoMode.Password)
        self.edtNewPWD = QLineEdit(self.gbxChangePWD)
        self.edtNewPWD.setObjectName(u"edtNewPWD")
        self.edtNewPWD.setGeometry(QRect(20, 70, 241, 21))
        self.edtNewPWD.setEchoMode(QLineEdit.EchoMode.Password)
        self.btnSavePWD = QPushButton(self.gbxChangePWD)
        self.btnSavePWD.setObjectName(u"btnSavePWD")
        self.btnSavePWD.setGeometry(QRect(270, 100, 101, 24))
        self.edtNewPWDConfirm = QLineEdit(self.gbxChangePWD)
        self.edtNewPWDConfirm.setObjectName(u"edtNewPWDConfirm")
        self.edtNewPWDConfirm.setGeometry(QRect(20, 100, 241, 21))
        self.edtNewPWDConfirm.setEchoMode(QLineEdit.EchoMode.Password)
        self.btnManagerPWDCFG = QPushButton(self.gbxChangePWD)
        self.btnManagerPWDCFG.setObjectName(u"btnManagerPWDCFG")
        self.btnManagerPWDCFG.setGeometry(QRect(586, 13, 21, 24))
        self.logMasterPWD = QTextEdit(self.gbxChangePWD)
        self.logMasterPWD.setObjectName(u"logMasterPWD")
        self.logMasterPWD.setGeometry(QRect(20, 130, 431, 101))
        self.logMasterPWD.setFrameShape(QFrame.Shape.NoFrame)

        self.gridLayout.addWidget(self.frameCFG_2, 0, 0, 1, 1)

        self.tabWidget.addTab(self.tab_config, "")
        self.tab_about = QWidget()
        self.tab_about.setObjectName(u"tab_about")
        self.gridLayout_3 = QGridLayout(self.tab_about)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.frame = QFrame(self.tab_about)
        self.frame.setObjectName(u"frame")
        self.frame.setStyleSheet(u"")
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.label_6 = QLabel(self.frame)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(110, 278, 151, 16))
        font = QFont()
        font.setBold(False)
        self.label_6.setFont(font)
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)
        self.lblIconAbout = QLabel(self.frame)
        self.lblIconAbout.setObjectName(u"lblIconAbout")
        self.lblIconAbout.setGeometry(QRect(780, 10, 45, 41))
        self.btnLnkReportABug = QCommandLinkButton(self.frame)
        self.btnLnkReportABug.setObjectName(u"btnLnkReportABug")
        self.btnLnkReportABug.setGeometry(QRect(50, 468, 140, 40))
        self.lblAboutInfo = QLabel(self.frame)
        self.lblAboutInfo.setObjectName(u"lblAboutInfo")
        self.lblAboutInfo.setGeometry(QRect(60, 278, 51, 111))
        font1 = QFont()
        font1.setBold(True)
        self.lblAboutInfo.setFont(font1)
        self.lblAboutInfo.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)
        self.lblAbout = QLabel(self.frame)
        self.lblAbout.setObjectName(u"lblAbout")
        self.lblAbout.setGeometry(QRect(60, 171, 621, 70))
        self.lblAbout.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)
        self.lblAbout.setWordWrap(True)
        self.lblLinkedIn = QLabel(self.frame)
        self.lblLinkedIn.setObjectName(u"lblLinkedIn")
        self.lblLinkedIn.setGeometry(QRect(118, 326, 151, 16))
        self.lblLinkedIn.setOpenExternalLinks(True)
        self.lblAboutTitle = QLabel(self.frame)
        self.lblAboutTitle.setObjectName(u"lblAboutTitle")
        self.lblAboutTitle.setGeometry(QRect(330, 60, 121, 40))
        font2 = QFont()
        font2.setPointSize(20)
        self.lblAboutTitle.setFont(font2)
        self.lblAboutTitle.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lblAboutSubtitle = QLabel(self.frame)
        self.lblAboutSubtitle.setObjectName(u"lblAboutSubtitle")
        self.lblAboutSubtitle.setGeometry(QRect(60, 150, 101, 20))
        font3 = QFont()
        font3.setPointSize(12)
        font3.setBold(True)
        self.lblAboutSubtitle.setFont(font3)
        self.lblAboutSubtitle.setStyleSheet(u"#label_7{\n"
"color:rgb(130, 130, 130)\n"
"}")
        self.lblAboutSubtitle.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)
        self.lblEmail = QLabel(self.frame)
        self.lblEmail.setObjectName(u"lblEmail")
        self.lblEmail.setGeometry(QRect(100, 343, 161, 16))
        self.lblEmail.setOpenExternalLinks(False)
        self.lblGitHub = QLabel(self.frame)
        self.lblGitHub.setObjectName(u"lblGitHub")
        self.lblGitHub.setGeometry(QRect(110, 310, 151, 16))
        self.lblGitHub.setOpenExternalLinks(True)
        self.lblVersion = QLabel(self.frame)
        self.lblVersion.setObjectName(u"lblVersion")
        self.lblVersion.setGeometry(QRect(111, 296, 151, 16))
        self.lblVersion.setFont(font)
        self.lblVersion.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)
        self.lblBG = QLabel(self.frame)
        self.lblBG.setObjectName(u"lblBG")
        self.lblBG.setGeometry(QRect(270, 260, 541, 251))
        self.lblBG.setStyleSheet(u"border: 0.2px solid #00ff00; /* Um verde bem \"cheguei\" pra voc\u00ea n\u00e3o perder de vista */\n"
"background-color: rgba(0, 255, 0, 10); /* Um fundo bem clarinho s\u00f3 pra marcar a \u00e1rea */")
        self.lblBG.setFrameShape(QFrame.Shape.StyledPanel)
        self.lblBG.setScaledContents(True)
        self.label_11 = QLabel(self.frame)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(683, 483, 120, 21))
        font4 = QFont()
        font4.setPointSize(12)
        self.label_11.setFont(font4)
        self.label_11.setStyleSheet(u"#label_11{\n"
"	background-color:rgb(45, 45, 45)\n"
"}")
        self.label_11.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btnLnkBuymeCoffee = QCommandLinkButton(self.frame)
        self.btnLnkBuymeCoffee.setObjectName(u"btnLnkBuymeCoffee")
        self.btnLnkBuymeCoffee.setGeometry(QRect(50, 424, 140, 40))
        self.btnLnkBuymeCoffee.setStyleSheet(u"#btnLnkBuymeCoffee {\n"
"	background-color:rgb(255, 216, 119);\n"
"	color:black;\n"
"}")

        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)

        self.tabWidget.addTab(self.tab_about, "")

        self.verticalLayout.addWidget(self.tabWidget)

        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setMinimumSize(QSize(0, 40))
        self.horizontalLayoutWidget = QWidget(self.widget)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(720, 7, 137, 30))
        self.hLayBtn = QHBoxLayout(self.horizontalLayoutWidget)
        self.hLayBtn.setObjectName(u"hLayBtn")
        self.hLayBtn.setContentsMargins(0, 0, 0, 0)
        self.btnClose = QPushButton(self.horizontalLayoutWidget)
        self.btnClose.setObjectName(u"btnClose")

        self.hLayBtn.addWidget(self.btnClose)


        self.verticalLayout.addWidget(self.widget)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 875, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setStyleSheet(u"")
        MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.tabWidget, self.btnSearchBy)
        QWidget.setTabOrder(self.btnSearchBy, self.btnSearch)
        QWidget.setTabOrder(self.btnSearch, self.edtSearch)
        QWidget.setTabOrder(self.edtSearch, self.treeCredentialsResponse)
        QWidget.setTabOrder(self.treeCredentialsResponse, self.edtAccount)
        QWidget.setTabOrder(self.edtAccount, self.edtURL)
        QWidget.setTabOrder(self.edtURL, self.edtPWD)
        QWidget.setTabOrder(self.edtPWD, self.btnShowPWD)
        QWidget.setTabOrder(self.btnShowPWD, self.btnNew)
        QWidget.setTabOrder(self.btnNew, self.btnApply)
        QWidget.setTabOrder(self.btnApply, self.btnCancel)
        QWidget.setTabOrder(self.btnCancel, self.edtPlainNotes)
        QWidget.setTabOrder(self.edtPlainNotes, self.cbxDefaultFieldSearch)
        QWidget.setTabOrder(self.cbxDefaultFieldSearch, self.cbxDefaultFieldOrder)
        QWidget.setTabOrder(self.cbxDefaultFieldOrder, self.edtCurrentPWD)
        QWidget.setTabOrder(self.edtCurrentPWD, self.edtNewPWD)
        QWidget.setTabOrder(self.edtNewPWD, self.edtNewPWDConfirm)
        QWidget.setTabOrder(self.edtNewPWDConfirm, self.btnSavePWD)
        QWidget.setTabOrder(self.btnSavePWD, self.btnLnkReportABug)
        QWidget.setTabOrder(self.btnLnkReportABug, self.btnClose)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.cbxDefaultFieldSearch.setCurrentIndex(0)
        self.cbxLogoffTime.setCurrentIndex(0)
        self.cbxColorScheme.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Hashed Maze", None))
#if QT_CONFIG(statustip)
        self.btnSearchBy.setStatusTip(QCoreApplication.translate("MainWindow", u"select the search field", None))
#endif // QT_CONFIG(statustip)
        self.btnSearchBy.setText(QCoreApplication.translate("MainWindow", u"search by", None))
        ___qtreewidgetitem = self.treeCredentialsResponse.headerItem()
        ___qtreewidgetitem.setText(5, QCoreApplication.translate("MainWindow", u"ACTION", None));
        ___qtreewidgetitem.setText(4, QCoreApplication.translate("MainWindow", u"ADDED AT", None));
        ___qtreewidgetitem.setText(3, QCoreApplication.translate("MainWindow", u"PASSWORD", None));
        ___qtreewidgetitem.setText(2, QCoreApplication.translate("MainWindow", u"NOTE", None));
        ___qtreewidgetitem.setText(1, QCoreApplication.translate("MainWindow", u"URL", None));
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("MainWindow", u"ACCOUNT", None));
        self.btnSearch.setText(QCoreApplication.translate("MainWindow", u"search", None))
#if QT_CONFIG(tooltip)
        self.lblIconSearch.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.lblIconSearch.setText(QCoreApplication.translate("MainWindow", u"ICON", None))
        self.edtURL.setPlaceholderText(QCoreApplication.translate("MainWindow", u"related site url", None))
        self.edtPWD.setPlaceholderText(QCoreApplication.translate("MainWindow", u"type/change your password", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"email account:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"URL:", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"pwd:", None))
        self.btnApply.setText(QCoreApplication.translate("MainWindow", u"apply", None))
#if QT_CONFIG(tooltip)
        self.btnShowPWD.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.btnShowPWD.setStatusTip(QCoreApplication.translate("MainWindow", u"show/hide password", None))
#endif // QT_CONFIG(statustip)
        self.btnShowPWD.setText("")
#if QT_CONFIG(statustip)
        self.btnNew.setStatusTip(QCoreApplication.translate("MainWindow", u"Click to start a new credential", None))
#endif // QT_CONFIG(statustip)
        self.btnNew.setText(QCoreApplication.translate("MainWindow", u"new", None))
#if QT_CONFIG(statustip)
        self.pBar.setStatusTip(QCoreApplication.translate("MainWindow", u"password strength", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(tooltip)
        self.frmStatusEdition.setToolTip(QCoreApplication.translate("MainWindow", u"feedback for editing status", None))
#endif // QT_CONFIG(tooltip)
        self.btnCancel.setText(QCoreApplication.translate("MainWindow", u"cancel", None))
#if QT_CONFIG(tooltip)
        self.btnHelpCredentials.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.btnHelpCredentials.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.btnHelpCredentials.setText(QCoreApplication.translate("MainWindow", u"?", None))
#if QT_CONFIG(tooltip)
        self.btnGenRandomPWD.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.btnGenRandomPWD.setStatusTip(QCoreApplication.translate("MainWindow", u"click to generate a random password", None))
#endif // QT_CONFIG(statustip)
        self.btnGenRandomPWD.setText(QCoreApplication.translate("MainWindow", u"random pass", None))
        self.lblStatusEditionOrError.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.lblSearchBy.setText(QCoreApplication.translate("MainWindow", u"search by...", None))
        self.lblResults.setText(QCoreApplication.translate("MainWindow", u"...", None))
#if QT_CONFIG(tooltip)
        self.btnHelpSearch.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.btnHelpSearch.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.btnHelpSearch.setText(QCoreApplication.translate("MainWindow", u"?", None))
#if QT_CONFIG(statustip)
        self.btnFirst.setStatusTip(QCoreApplication.translate("MainWindow", u"first page", None))
#endif // QT_CONFIG(statustip)
        self.btnFirst.setText("")
#if QT_CONFIG(statustip)
        self.btnGoBack.setStatusTip(QCoreApplication.translate("MainWindow", u"prvious page", None))
#endif // QT_CONFIG(statustip)
        self.btnGoBack.setText("")
#if QT_CONFIG(statustip)
        self.btnGoForward.setStatusTip(QCoreApplication.translate("MainWindow", u"next page", None))
#endif // QT_CONFIG(statustip)
        self.btnGoForward.setText("")
#if QT_CONFIG(statustip)
        self.btnLast.setStatusTip(QCoreApplication.translate("MainWindow", u"last page", None))
#endif // QT_CONFIG(statustip)
        self.btnLast.setText("")
        self.lblPagination.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_search), QCoreApplication.translate("MainWindow", u"Search", None))
        self.lblIconConfig.setText(QCoreApplication.translate("MainWindow", u"ICON", None))
        self.gbxGeneral.setTitle(QCoreApplication.translate("MainWindow", u" General configuration ", None))
        self.cbxDefaultFieldSearch.setItemText(0, QCoreApplication.translate("MainWindow", u"all fields", None))
        self.cbxDefaultFieldSearch.setItemText(1, QCoreApplication.translate("MainWindow", u"created_at", None))
        self.cbxDefaultFieldSearch.setItemText(2, QCoreApplication.translate("MainWindow", u"user", None))
        self.cbxDefaultFieldSearch.setItemText(3, QCoreApplication.translate("MainWindow", u"url", None))
        self.cbxDefaultFieldSearch.setItemText(4, QCoreApplication.translate("MainWindow", u"notes", None))

        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Default field search:", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Order results by:", None))
        self.cbxDefaultFieldOrder.setItemText(0, QCoreApplication.translate("MainWindow", u"created_at", None))
        self.cbxDefaultFieldOrder.setItemText(1, QCoreApplication.translate("MainWindow", u"user", None))
        self.cbxDefaultFieldOrder.setItemText(2, QCoreApplication.translate("MainWindow", u"url", None))

#if QT_CONFIG(tooltip)
        self.btnGeneralCFG.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.btnGeneralCFG.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.btnGeneralCFG.setText(QCoreApplication.translate("MainWindow", u"?", None))
        self.lblSettings.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.cbxLogoffTime.setItemText(0, QCoreApplication.translate("MainWindow", u"-", None))
        self.cbxLogoffTime.setItemText(1, QCoreApplication.translate("MainWindow", u"120000", None))
        self.cbxLogoffTime.setItemText(2, QCoreApplication.translate("MainWindow", u"300000", None))
        self.cbxLogoffTime.setItemText(3, QCoreApplication.translate("MainWindow", u"600000", None))

        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Logoff time:", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Color scheme:", None))
        self.cbxColorScheme.setItemText(0, QCoreApplication.translate("MainWindow", u"tokio_night", None))
        self.cbxColorScheme.setItemText(1, QCoreApplication.translate("MainWindow", u"catppuccin_mocha", None))
        self.cbxColorScheme.setItemText(2, QCoreApplication.translate("MainWindow", u"dracula", None))
        self.cbxColorScheme.setItemText(3, QCoreApplication.translate("MainWindow", u"nord", None))
        self.cbxColorScheme.setItemText(4, QCoreApplication.translate("MainWindow", u"gruvbox", None))
        self.cbxColorScheme.setItemText(5, QCoreApplication.translate("MainWindow", u"one_dark", None))
        self.cbxColorScheme.setItemText(6, QCoreApplication.translate("MainWindow", u"system", None))

        self.lblCFGDatabaseDirectory.setText(QCoreApplication.translate("MainWindow", u"path", None))
        self.lblCFGDatabaseDirectory_Title.setText(QCoreApplication.translate("MainWindow", u"database directory:", None))
        self.gbxChangePWD.setTitle(QCoreApplication.translate("MainWindow", u" Manage master password ", None))
        self.edtCurrentPWD.setPlaceholderText(QCoreApplication.translate("MainWindow", u"type your actual password", None))
        self.edtNewPWD.setPlaceholderText(QCoreApplication.translate("MainWindow", u"type new password", None))
        self.btnSavePWD.setText(QCoreApplication.translate("MainWindow", u"save password", None))
        self.edtNewPWDConfirm.setPlaceholderText(QCoreApplication.translate("MainWindow", u"repeat new password", None))
#if QT_CONFIG(tooltip)
        self.btnManagerPWDCFG.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.btnManagerPWDCFG.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.btnManagerPWDCFG.setText(QCoreApplication.translate("MainWindow", u"?", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_config), QCoreApplication.translate("MainWindow", u"Config", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Tito de Barros Junior", None))
        self.lblIconAbout.setText(QCoreApplication.translate("MainWindow", u"ICON", None))
        self.btnLnkReportABug.setText(QCoreApplication.translate("MainWindow", u"report a bug", None))
        self.lblAboutInfo.setText(QCoreApplication.translate("MainWindow", u"Author: \n"
"Version: \n"
"GitHub: \n"
"LinkedIn:\n"
"Email: \n"
"", None))
        self.lblAbout.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>A secure vault for organizing passwords, notes, and sensitive information with quick access and reliable protection.</p><p>Encryption powered by AES-256-GCM with unique nonces per entry, keys derived via PBKDF2-HMAC-SHA256, and master password hashed with bcrypt.</p></body></html>", None))
        self.lblLinkedIn.setText(QCoreApplication.translate("MainWindow", u"<a href=\"https://www.linkedin.com/in/titobarros/\">linkedin.com/in/titobarros/</a>", None))
        self.lblAboutTitle.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.lblAboutSubtitle.setText(QCoreApplication.translate("MainWindow", u"HashedMaze", None))
        self.lblEmail.setText(QCoreApplication.translate("MainWindow", u"<span>titobarrosjr@protonmail.com</span>", None))
        self.lblGitHub.setText(QCoreApplication.translate("MainWindow", u"<a href=\"https://github.com/TitoBarrosTI\">github.com/TitoBarrosTI</a>", None))
        self.lblVersion.setText(QCoreApplication.translate("MainWindow", u"--version--", None))
        self.lblBG.setText("")
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"#HashedMaze", None))
        self.btnLnkBuymeCoffee.setText(QCoreApplication.translate("MainWindow", u"buy me a coffee :)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_about), QCoreApplication.translate("MainWindow", u"About", None))
        self.btnClose.setText(QCoreApplication.translate("MainWindow", u"close", None))
    # retranslateUi

